apiVersion: apps/v1
kind: Deployment
metadata:
  name: rundeck
  namespace: profarma-poc
  labels:
    app: rundeck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rundeck
  template:
    metadata:
      labels:
        app: rundeck
    spec:
      containers:
        - name: rundeck
          image: rundeck/rundeck:5.20.1
          ports:
            - containerPort: 4440
              name: http
          env:
            - name: RUNDECK_GRAILS_URL
              value: "http://rundeck.local"
            - name: RUNDECK_SERVER_SESSION_TIMEOUT
              value: "86400"
            - name: JVM_MAX_RAM_PERCENTAGE
              value: "50"
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx768m -XX:+UseContainerSupport -XX:MaxRAMPercentage=50.0"
          volumeMounts:
            - name: data
              mountPath: /home/rundeck/server/data
          livenessProbe:
            httpGet:
              path: /
              port: 4440
            initialDelaySeconds: 120
            periodSeconds: 60
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 4440
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 10
          resources:
            requests:
              memory: "768Mi"
              cpu: "250m"
            limits:
              memory: "1280Mi"
              cpu: "1500m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rundeck-data
