apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rundeck-data
  namespace: profarma-poc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
